[data]
working_dir = "build"

[data.columns]
description = "description"
project = "projectName"
client = "clientName"
datetime = "timeInterval.start"
duration = "timeInterval.duration"

[logging]
file_config = "logging.ini"